# Generated by Django 4.0.6 on 2022-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.PositiveSmallIntegerField(max_length=4)),
                ('event_time', models.TimeField()),
            ],
        ),
    ]
