# Generated by Django 4.0.6 on 2022-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_det',
            name='slot_no',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
