# Generated by Django 4.0.6 on 2022-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_data', '0002_alter_slot_det_slot_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_det',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
