# Generated by Django 4.0.6 on 2022-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_data', '0003_slot_det_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_det',
            name='status',
            field=models.IntegerField(),
        ),
    ]
